# Site settings
title: d.kebi.log
email: dotkebi@gmail.com
description: "software engineer Myoung-jin, Ko(AKA. dotkebi)"
baseurl: ""
url: "http://dotkebi.github.io"
#twitter_username: jekyllrb
github_username:  dotkebi

# Build settings
markdown: kramdown
permalink: pretty
theme: minima
