# Site settings
title: d.kebi.log
email: dotkebi@gmail.com
name: "Myoung-jin, Ko"
description: "software engineer Myoung-jin, Ko(AKA. dotkebi)"
baseurl: ""
url: "http://dotkebi.github.io"
alias: "dotkebi"
github_username: "dotkebi"
linkedin_username: "명진-고-607272b7"

# Build settings
markdown: kramdown
permalink: pretty
theme: minima

gems:
  - jekyll-sitemap
